import {useState} from 'react';
import {statistics,weightedGrade,validateCsv,units,convertUnit} from '../data/calculations';
import {track} from '../api';
export default function LocalTool({tool}){
 const [text,setText]=useState(''),[result,setResult]=useState(null),[error,setError]=useState(''),[a,setA]=useState(''),[b,setB]=useState(''),[scale,setScale]=useState(4),[group,setGroup]=useState('Length'),[from,setFrom]=useState('m'),[to,setTo]=useState('km'),[mode,setMode]=useState('of');
 const isGrade=['gpa-calculator','cgpa-calculator'].includes(tool.slug),isPercent=tool.slug==='percentage-calculator',isUnit=tool.slug==='unit-converter';
 const clear=()=>{setResult(null);setError('');};
 const execute=action=>{clear();try{
  if(new TextEncoder().encode(text).length>1024*1024)throw new Error('Use no more than 1 MB of text.');
  let output;
  if(tool.kind==='json'){const parsed=JSON.parse(text);output=tool.slug==='json-validator'?{Valid:true,'Top-level type':parsed===null?'null':Array.isArray(parsed)?'array':typeof parsed}:JSON.stringify(parsed,null,action==='minify'?0:2);}
  else if(tool.kind==='csv')output=validateCsv(text);
  else if(isGrade)output=weightedGrade(text,Number(scale));
  else if(isPercent){if(!a.trim()||!b.trim()||![Number(a),Number(b)].every(Number.isFinite))throw new Error('Enter two finite numbers.');if(mode==='change'&&Number(a)===0)throw new Error('Percentage change is undefined when the original value is zero.');output=mode==='of'?{Result:Number(a)/100*Number(b)}:{'Percentage change':(Number(b)-Number(a))/Math.abs(Number(a))*100};}
  else if(isUnit){if(!a.trim())throw new Error('Enter a value to convert.');output={[to]:convertUnit(Number(a),group,from,to)};}
  else output=statistics(text);
  if(typeof output==='object'&&Object.values(output).some(v=>typeof v==='number'&&!Number.isFinite(v)))throw new Error('The result exceeds the supported numeric range.');
  setResult(output);track('calculator_used',tool.slug);
 }catch(e){setError(e.message);track('error_occurred',tool.slug);}};
 const copy=async()=>{try{await navigator.clipboard.writeText(typeof result==='string'?result:JSON.stringify(result,null,2));}catch{setError('Clipboard access is unavailable. Select and copy the result text.');}};
 return <section className="tool-workspace local-tool"><p className="privacy-note">Runs entirely in your browser. Your input is not uploaded.</p><form onSubmit={e=>{e.preventDefault();execute();}} onChange={clear}>
 {isPercent?<><label>Calculation<select value={mode} onChange={e=>setMode(e.target.value)}><option value="of">A percent of B</option><option value="change">Percentage change from A to B</option></select></label><div className="form-grid"><label>{mode==='of'?'Percentage (A)':'Original value (A)'}<input type="number" step="any" value={a} onChange={e=>setA(e.target.value)} required/></label><label>{mode==='of'?'Number (B)':'New value (B)'}<input type="number" step="any" value={b} onChange={e=>setB(e.target.value)} required/></label></div><p className="muted">{mode==='of'?'Formula: A ÷ 100 × B.':'Formula: (B − A) ÷ |A| × 100. Undefined when A is zero.'}</p></>
 :isUnit?<><div className="form-grid"><label>Quantity<select value={group} onChange={e=>{setGroup(e.target.value);const names=Object.keys(units[e.target.value]);setFrom(names[0]);setTo(names[1]);}}>{Object.keys(units).map(k=><option key={k}>{k}</option>)}</select></label><label>Value<input type="number" step="any" required value={a} onChange={e=>setA(e.target.value)}/></label><label>From<select value={from} onChange={e=>setFrom(e.target.value)}>{Object.keys(units[group]).map(k=><option key={k}>{k}</option>)}</select></label><label>To<select value={to} onChange={e=>setTo(e.target.value)}>{Object.keys(units[group]).map(k=><option key={k}>{k}</option>)}</select></label></div><p className="muted">Length and mass use fixed SI conversion factors. Temperature uses Celsius, Fahrenheit and Kelvin formulas.</p></>
 :<>{isGrade&&<><label>Maximum grade scale<input type="number" min="0.1" max="100" step="any" required value={scale} onChange={e=>setScale(e.target.value)}/></label><p>Enter numeric grade points and credits, one pair per line. Result = sum of grade × credits ÷ total credits. Use your institution’s grade-point mapping; percentages are not assumed.</p></>}<label>{tool.kind==='json'?'JSON input':tool.kind==='csv'?'CSV input':isGrade?'Grade,credits pairs':'Numbers (separated by spaces or commas)'}<textarea required rows={10} spellCheck={false} value={text} onChange={e=>setText(e.target.value)} placeholder={tool.kind==='json'?' {"name": "DataSphere", "values": [1, 2, 3]}':tool.kind==='csv'?'name,value\nAlice,10\nBob,20':isGrade?'3.5,4\n3.8,3':'10, 20, 30, 40'}/></label>{tool.slug==='statistics-calculator'&&<p className="muted">Variance and standard deviation use the sample formula (n − 1). Single-value sample variance is undefined.</p>}</>}
 <div className="actions"><button className="primary" type="submit">{tool.kind==='calculator'?'Calculate':tool.slug==='json-formatter'?'Format JSON':'Validate'}</button>{tool.slug==='json-formatter'&&<button type="button" onClick={()=>execute('minify')}>Minify</button>}<button type="button" onClick={()=>{setText('');setA('');setB('');clear();}}>Clear</button></div></form>{error&&<p className="error" role="alert">{error}</p>}<section className="result" aria-live="polite"><h2>Result</h2>{result===null?<p>Your result will appear here.</p>:<>{typeof result==='string'?<pre tabIndex={0}>{result}</pre>:<dl>{Object.entries(result).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{typeof v==='number'?Number(v.toPrecision(12)).toLocaleString(undefined,{maximumFractionDigits:10}):String(v)}</dd></div>)}</dl>}<button onClick={copy}>Copy result</button></>}</section></section>
}
