import fs from 'node:fs';
import path from 'node:path';
import {loadEnv} from 'vite';
import {tools,faqsFor,toolPath} from '../src/data/tools.js';
const env=loadEnv('production',process.cwd(),'');
const origin=(process.env.VITE_SITE_URL||env.VITE_SITE_URL||'http://localhost:8000').replace(/\/$/,'');
if(!/^https?:\/\//.test(origin))throw new Error('VITE_SITE_URL must be an absolute HTTP(S) URL');
const base=fs.readFileSync('dist/index.html','utf8');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const links=items=>items.map(t=>`<article><h2><a href="${toolPath(t)}">${esc(t.name)}</a></h2><p>${esc(t.description)}</p></article>`).join('');
const pages=[{path:'/',title:'Free Online Data Analytics & Data Tools | DataSphere AI',description:'Free online tools for CSV, Excel, JSON, data cleaning, visualization and calculations.',body:`<h1>Analyze, Clean &amp; Transform Your Data Online</h1><p>Free tools. No account required.</p><a href="/tools">Explore All Tools</a>${links(tools)}`},{path:'/tools',title:'All Free Data Tools | DataSphere AI',description:'Explore free analysis, cleaning, conversion, visualization and calculator tools.',body:`<h1>All Tools</h1>${links(tools)}`},...tools.map(t=>({path:toolPath(t),title:`${t.name} — Free Online Tool | DataSphere AI`,description:t.description,tool:t,body:`<nav aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/tools">Tools</a> / ${esc(t.name)}</nav><h1>${esc(t.name)}</h1><p>${esc(t.description)}</p><p>Enable JavaScript to use this interactive tool. No account is required.</p><h2>How to use ${esc(t.name)}</h2><ol><li>${t.accept?`Choose a ${esc(t.accept)} file up to 10 MB.`:'Enter your input in the tool.'}</li><li>${t.kind==='clean'?'Choose an operation and inspect the before and after preview.':'Run the tool and review the results.'}</li><li>${t.accept?'Download the result and delete the dataset when finished.':'Copy your result or adjust the inputs.'}</li></ol><h2>Features</h2><p>${esc(t.description)}</p><h2>Frequently asked questions</h2>${faqsFor(t).map(f=>`<h3>${esc(f.q)}</h3><p>${esc(f.a)}</p>`).join('')}<h2>Related tools</h2>${links(tools.filter(r=>r.category===t.category&&r.slug!==t.slug).slice(0,4))}`})),...['privacy','terms','contact'].map(p=>({path:`/${p}`,title:`${p[0].toUpperCase()+p.slice(1)} | DataSphere AI`,description:'DataSphere platform information.',body:`<h1>${p[0].toUpperCase()+p.slice(1)}</h1><p>Enable JavaScript to read installation details.</p>`}))];
for(const p of pages){
 const url=origin+p.path;
 const graph=p.tool?[{'@type':'WebApplication',name:p.tool.name,url,applicationCategory:'UtilitiesApplication',operatingSystem:'Any',offers:{'@type':'Offer',price:'0',priceCurrency:'USD'}},{'@type':'BreadcrumbList',itemListElement:[{name:'Home',item:origin+'/'},{name:'Tools',item:origin+'/tools'},{name:p.tool.name,item:url}].map((v,i)=>({'@type':'ListItem',position:i+1,...v}))},{'@type':'FAQPage',mainEntity:faqsFor(p.tool).map(f=>({'@type':'Question',name:f.q,acceptedAnswer:{'@type':'Answer',text:f.a}}))}]:[{'@type':'WebSite',name:'DataSphere AI',url}];
 const meta=`<link rel="canonical" href="${esc(url)}"/><meta property="og:title" content="${esc(p.title)}"/><meta property="og:description" content="${esc(p.description)}"/><meta property="og:url" content="${esc(url)}"/><meta property="og:type" content="website"/><meta name="twitter:card" content="summary"/><meta name="twitter:title" content="${esc(p.title)}"/><meta name="twitter:description" content="${esc(p.description)}"/><script id="page-schema" type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph}).replace(/</g,'\\u003c')}</script>`;
 const html=base.replace(/<title>.*?<\/title>/,`<title>${esc(p.title)}</title>`).replace(/<meta name="description"[^>]*>/,`<meta name="description" content="${esc(p.description)}"/>`).replace('</head>',meta+'</head>').replace('<div id="root"></div>',`<div id="root"><main>${p.body}</main></div>`);
 const dir=path.join('dist',p.path);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html);
}
fs.writeFileSync('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(p=>`<url><loc>${esc(origin+p.path)}</loc></url>`).join('')}</urlset>`);
fs.writeFileSync('dist/robots.txt',`User-agent: *\nAllow: /\nDisallow: /api/\nSitemap: ${origin}/sitemap.xml\n`);
console.log(`Prerendered ${pages.length} pages. Canonical origin: ${origin}`);
